var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/analytics/route.js")
R.c("server/chunks/[root-of-the-server]__0f5486c1._.js")
R.c("server/chunks/node_modules_next_92aaecbe._.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/node_modules_9e1fbe53._.js")
R.c("server/chunks/[root-of-the-server]__c38aa704._.js")
R.c("server/chunks/node_modules_next_dist_23bfe24c._.js")
R.c("server/chunks/_next-internal_server_app_api_analytics_route_actions_ac389de2.js")
R.m(26378)
module.exports=R.m(26378).exports
