module.exports=[93695,(a,b,c)=>{b.exports=a.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},43619,a=>{a.n(a.i(79962))},13718,a=>{a.n(a.i(85523))},18198,a=>{a.n(a.i(45518))},62212,a=>{a.n(a.i(66114))},30419,a=>{a.n(a.i(27641))},12860,a=>{"use strict";let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call KanbanBoard() from the server but KanbanBoard is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/admin/KanbanBoard.tsx <module evaluation>","KanbanBoard");a.s(["KanbanBoard",0,b])},48450,a=>{"use strict";let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call KanbanBoard() from the server but KanbanBoard is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/admin/KanbanBoard.tsx","KanbanBoard");a.s(["KanbanBoard",0,b])},12478,a=>{"use strict";a.i(12860);var b=a.i(48450);a.n(b)},40088,a=>{"use strict";var b=a.i(7997),c=a.i(96942),d=a.i(82248);let e=(0,c.cva)("inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",{variants:{variant:{default:"border-transparent bg-primary text-primary-foreground hover:bg-primary/80",secondary:"border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",destructive:"border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",outline:"text-foreground"}},defaultVariants:{variant:"default"}});function f({className:a,variant:c,...f}){return(0,b.jsx)("div",{className:(0,d.cn)(e({variant:c}),a),...f})}a.s(["Badge",()=>f])},57127,a=>{"use strict";var b=a.i(7997);a.i(42537);var c=a.i(5860),d=a.i(5246),e=a.i(12478),f=a.i(40088);async function g(){let g=await (0,d.cookies)(),{getCurrentUser:h}=await a.A(51587),{data:{user:i}}=await h();if(!i)return(0,b.jsx)("div",{className:"text-red-500 p-8",children:"Unauthorized"});let j=i.id.startsWith("00000000-0000-0000-0000-0000000000")?process.env.SUPABASE_SERVICE_ROLE_KEY:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYXhqZG1vZnFiY29sanhnbndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2ODM3MjcsImV4cCI6MjA4MDI1OTcyN30.zTcpvbRKcWJ4ecPKxgWUUvTaYC7wpB2s8SxFxE3IH8c",k=(0,c.createServerClient)("https://inaxjdmofqbcoljxgnwr.supabase.co",j,{cookies:{get:a=>g.get(a)?.value,set(a,b,c){g.set({name:a,value:b,...c})},remove(a,b){g.set({name:a,value:"",...b})}}}),{data:l,error:m}=await k.from("applications").select(`
            *,
            profiles (
                email,
                first_name,
                last_name
            )
        `).order("created_at",{ascending:!1});return m?(0,b.jsxs)("div",{className:"text-red-500 p-8",children:["Error loading applications: ",m.message]}):(0,b.jsxs)("div",{className:"h-[calc(100vh-64px)] flex flex-col p-6 bg-gray-50 overflow-y-auto",children:[(0,b.jsxs)("div",{className:"flex justify-between items-center mb-6",children:[(0,b.jsxs)("div",{children:[(0,b.jsx)("h1",{className:"text-2xl font-bold text-gray-900",children:"Agent Portal"}),(0,b.jsx)("p",{className:"text-sm text-gray-500",children:"Manage client applications and DS-160 registrations"})]}),(0,b.jsxs)("div",{className:"flex gap-2",children:[(0,b.jsxs)(f.Badge,{variant:"outline",className:"bg-white",children:["Queue: ",l?.length||0]}),(0,b.jsx)(f.Badge,{className:"bg-indigo-600",children:"Agent Mode"})]})]}),(0,b.jsx)("div",{className:"flex-1 space-y-8 pb-10",children:(0,b.jsx)(e.KanbanBoard,{applications:l||[]})})]})}a.s(["default",()=>g])},51587,a=>{a.v(b=>Promise.all(["server/chunks/ssr/lib_auth_current-user_ts_f489f1ad._.js"].map(b=>a.l(b))).then(()=>b(24870)))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__4b8a2c35._.js.map