module.exports=[37688,a=>{"use strict";var b=a.i(7997),c=a.i(37936);a.i(42537);var d=a.i(5860),e=a.i(5246),f=a.i(18558);async function g(c,g){let h=await (0,e.cookies)(),i=(0,d.createServerClient)("https://inaxjdmofqbcoljxgnwr.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluYXhqZG1vZnFiY29sanhnbndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2ODM3MjcsImV4cCI6MjA4MDI1OTcyN30.zTcpvbRKcWJ4ecPKxgWUUvTaYC7wpB2s8SxFxE3IH8c",{cookies:{get:a=>h.get(a)?.value,set(a,b,c){h.set({name:a,value:b,...c})},remove(a,b){h.set({name:a,value:"",...b})}}}),{data:{user:j},error:k}=await i.auth.getUser();if(k||!j)throw Error("Unauthorized: You must be logged in to perform this action.");let{error:l}=await i.from("applications").update({status:g}).eq("id",c);if(l)throw Error(l.message);if("completed_delivered"===g)try{let{data:d}=await i.from("applications").select("*, profiles (email)").eq("id",c).single(),e=d.client_metadata?.locale||"es",{getTranslations:f}=await a.A(26238),g=await f({locale:e,namespace:"Email"}),{renderToBuffer:h}=await a.A(3632),{DS160Document:j}=await a.A(71879),k=await h((0,b.jsx)(j,{data:d.ds160_payload})),{sendEmail:l}=await a.A(75434);await l({to:d.profiles.email,subject:g("applicationCompletedSubject"),html:`
                        <h1>${g("applicationCompletedHeader")}</h1>
                        <p>${g("dearApplicant")}</p>
                        <p>${g("applicationProcessed")}</p>
                        <p>${g("findAttached")}</p>
                        <br/>
                        <p>${g("bestRegards")}</p>
                        <p>${g("companyName")}</p>
                    `,attachments:[{filename:`DS160_${d.id}.pdf`,content:k}]})}catch(a){console.error("Failed to send completion email:",a)}return(0,f.revalidatePath)("/admin"),(0,f.revalidatePath)("/dashboard"),{success:!0}}(0,a.i(13095).ensureServerEntryExports)([g]),(0,c.registerServerReference)(g,"60e06198f0f33d9f7a6e4c93218b0b00d367e9df83",null),a.s(["updateStatus",()=>g])},87136,a=>{"use strict";var b=a.i(37688);a.s([],96669),a.i(96669),a.s(["60e06198f0f33d9f7a6e4c93218b0b00d367e9df83",()=>b.updateStatus],87136)},26238,a=>{a.v(b=>Promise.all(["server/chunks/ssr/node_modules_next-intl_dist_esm_production_e4ae562d._.js"].map(b=>a.l(b))).then(()=>b(33407)))},3632,a=>{a.v(b=>Promise.all(["server/chunks/ssr/[externals]_@react-pdf_renderer_5b366df1._.js"].map(b=>a.l(b))).then(()=>b(20267)))},71879,a=>{a.v(b=>Promise.all(["server/chunks/ssr/[root-of-the-server]__82e77341._.js"].map(b=>a.l(b))).then(()=>b(25472)))},75434,a=>{a.v(b=>Promise.all(["server/chunks/ssr/[externals]_node:crypto_c20cce38._.js","server/chunks/ssr/_b6bff5ec._.js"].map(b=>a.l(b))).then(()=>b(55988)))}];

//# sourceMappingURL=%5Broot-of-the-server%5D__521b3858._.js.map