import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import { DS160Payload } from '@/types/ds160';

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: 1,
        borderBottomColor: '#000',
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    subtitle: {
        fontSize: 12,
        textAlign: 'center',
        marginTop: 5,
        color: '#666',
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        backgroundColor: '#f0f0f0',
        padding: 5,
        marginBottom: 10,
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        width: '40%',
        fontSize: 10,
        fontWeight: 'bold',
    },
    value: {
        width: '60%',
        fontSize: 10,
    },
});

interface DS160DocumentProps {
    data: DS160Payload;
}

export const DS160Document = ({ data }: DS160DocumentProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>DS-160 Application Data</Text>
                <Text style={styles.subtitle}>US Visa Processing Center - Official Copy</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Personal Information</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Surnames:</Text>
                    <Text style={styles.value}>{data.ds160_data.personal.surnames || 'N/A'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Given Names:</Text>
                    <Text style={styles.value}>{data.ds160_data.personal.given_names || 'N/A'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Date of Birth:</Text>
                    <Text style={styles.value}>{data.ds160_data.personal.dob || 'N/A'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Marital Status:</Text>
                    <Text style={styles.value}>{data.ds160_data.personal.marital_status || 'N/A'}</Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Travel Information</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Purpose of Trip:</Text>
                    <Text style={styles.value}>{data.ds160_data.travel.purpose_code || 'N/A'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Payer:</Text>
                    <Text style={styles.value}>{data.ds160_data.travel.paying_entity || 'N/A'}</Text>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Work & Education</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Current Employer:</Text>
                    <Text style={styles.value}>{data.ds160_data.work_history.current_job.employer_name || 'N/A'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Job Title (EN):</Text>
                    <Text style={styles.value}>{data.ds160_data.work_history.current_job.job_title_translated_en || 'N/A'}</Text>
                </View>
            </View>

            <Text style={{ position: 'absolute', bottom: 30, left: 0, right: 0, textAlign: 'center', fontSize: 8, color: '#999' }}>
                Generated by US Visa Processing Center AI System
            </Text>
        </Page>
    </Document>
);
