// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/about" | "/[locale]/admin" | "/[locale]/agent" | "/[locale]/assessment" | "/[locale]/assessment/b1b2" | "/[locale]/assessment/business" | "/[locale]/assessment/diy" | "/[locale]/assessment/full" | "/[locale]/assessment/simulator" | "/[locale]/assessment/student" | "/[locale]/auth/auth-code-error" | "/[locale]/contact" | "/[locale]/dashboard" | "/[locale]/login" | "/[locale]/profile" | "/[locale]/register" | "/[locale]/scan" | "/[locale]/services" | "/[locale]/success" | "/[locale]/support" | "/[locale]/verify"
type AppRouteHandlerRoutes = "/api/analytics" | "/api/applications/draft" | "/api/chat" | "/api/checkout" | "/api/contact" | "/api/extension/data" | "/api/webhooks" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/[locale]" | "/[locale]/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/agent": { "locale": string; }
  "/[locale]/assessment": { "locale": string; }
  "/[locale]/assessment/b1b2": { "locale": string; }
  "/[locale]/assessment/business": { "locale": string; }
  "/[locale]/assessment/diy": { "locale": string; }
  "/[locale]/assessment/full": { "locale": string; }
  "/[locale]/assessment/simulator": { "locale": string; }
  "/[locale]/assessment/student": { "locale": string; }
  "/[locale]/auth/auth-code-error": { "locale": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/dashboard": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/profile": { "locale": string; }
  "/[locale]/register": { "locale": string; }
  "/[locale]/scan": { "locale": string; }
  "/[locale]/services": { "locale": string; }
  "/[locale]/success": { "locale": string; }
  "/[locale]/support": { "locale": string; }
  "/[locale]/verify": { "locale": string; }
  "/api/analytics": {}
  "/api/applications/draft": {}
  "/api/chat": {}
  "/api/checkout": {}
  "/api/contact": {}
  "/api/extension/data": {}
  "/api/webhooks": {}
  "/auth/callback": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
  "/[locale]/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
